
COMMAND_ENABLE=yes
DEBUG_ENABLE = yes
CONSOLE_ENABLE = yes

TAP_DANCE_ENABLE = yes

NKRO_ENABLE      = no
BACKLIGHT_ENABLE = no 
MIDI_ENABLE      = no 
AUDIO_ENABLE     = no 
UNICODE_ENABLE   = no 
BLUETOOTH_ENABLE = no 
RGBLIGHT_ENABLE  = no 
SLEEP_LED_ENABLE = no 

