
# 
# SLEEP_LED_ENABLE=no

COMMAND_ENABLE=yes
# BOOTMAGIC_ENABLE=yes
DEBUG_ENABLE = yes
CONSOLE_ENABLE = yes
#TAP_DANCE_ENABLE = yes

# AUTOLOG_ENABLE = no
# ifeq (${AUTOLOG_ENABLE},yes)
# KEYLOGGER_ENABLE = yes
# OPT_DEFS += -DAUTOLOG_ENABLE
# endif

# KEYLOGGER_ENABLE = yes
# ifeq (${KEYLOGGER_ENABLE},yes)
# OPT_DEFS += -DKEYLOGGER_ENABLE
# CONSOLE_ENABLE = yes
# endif


# BOOTMAGIC_ENABLE = no  # Virtual DIP switch configuration(+1000)
# MOUSEKEY_ENABLE  = no  # Mouse keys(+4700)
# EXTRAKEY_ENABLE  = yes # Audio control and System control(+450)
# CONSOLE_ENABLE   = no  # Console for debug(+400)
# COMMAND_ENABLE   = no  # Commands for debug and configuration
# NKRO_ENABLE      = yes # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ # nkro-doesnt-work
BACKLIGHT_ENABLE = no  # Enable keyboard backlight functionality
MIDI_ENABLE      = no  # MIDI controls
AUDIO_ENABLE     = no  # Audio output on port C6
UNICODE_ENABLE   = no  # Unicode
BLUETOOTH_ENABLE = no  # Enable Bluetooth with the Adafruit EZ-Key HID
RGBLIGHT_ENABLE  = no  # Enable WS2812 RGB underlight.  Do not enable this with audio at the same time.
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend


ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
